name: endpoint
description: "A professional API client for mobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  animations: ^2.0.8
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
